module.exports = {
  multer: {
    mimeTypes: {
      audio: [
        'audio/mpeg',
        'audio/midi',
        'audio/x-midi',
        'audio/ogg',
        'audio/opus',
        'audio/wav',
        'audio/webm',
      ],
      image: [
        'image/png',
        'image/jpg',
        'image/jpeg',
        'image/gif',
        'image/svg+xml',
      ],
      video: [
        'video/x-msvideo',
        'video/mp4',
        'video/mpeg',
        'video/ogg',
        'video/webm',
        'video/3gpp',
      ],
    },
    fileTypes: ['image', 'images', 'audio', 'video'],
    multerError: {
      audio:
        'Audio must be .mpeg, .mp3, .mpeg3, .mid .midi, .oga, .opus, .wav, .weba format',
      image: 'Image must be .png, .jpg, .gif, .svg and .jpeg format',
      video: 'Video must be .avi, .mp4, .mpeg, .ogv, .webm and .3gp format',
    },
    multerFileSizeLimit: {
      audio: 1024 * 1024 * 10, // 10MB
      image: 1024 * 1024 * 10,
      video: 1024 * 1024 * 50, // 50MB
    },
    maxCount: {
      images: 10,
    },
  },
  ListCities: [
    'An Giang',
    'Bà Rịa Vũng Tàu',
    'Bình Dương',
    'Bình Phước',
    'Bình Thuận',
    'Bình Định',
    'Bạc Liêu',
    'Bắc Cạn',
    'Bắc Giang',
    'Bắc Ninh',
    'Bến Tre',
    'Cao Bằng',
    'Cà Mau',
    'Cần Thơ',
    'Đà Nẵng',
    'Đăk Lăk',
    'Điện Biên',
    'Đồng Nai',
    'Đồng Tháp',
    'Gia Lai',
    'Hà Giang',
    'Hà Nam',
    'Hà Nội',
    'Hà Tây',
    'Hà Tĩnh',
    'Hà Đông',
    'Hòa Bình',
    'Hưng Yên',
    'Hạ Long',
    'Hải Dương',
    'Hải Phòng',
    'Hồ Chí Minh',
    'Khánh Hòa',
    'Kiên Giang',
    'KonTum',
    'Lai Châu',
    'Long An',
    'Lào Cai',
    'Lâm Đồng',
    'Lạng Sơn',
    'Nam Định',
    'Nghệ An',
    'Ninh Bình',
    'Ninh Thuận',
    'Phú Thọ',
    'Phú Yên',
    'Quảng Bình',
    'Quảng Nam',
    'Quảng Ngãi',
    'Quảng Ninh',
    'Quảng Trị',
    'Sóc Trăng',
    'Sơn La',
    'Thanh Hóa',
    'Thái Bình',
    'Thái Nguyên',
    'Thừa Thiên Huế',
    'Tiền Giang',
    'Trà Vinh',
    'Tuyên Quang',
    'Tây Ninh',
    'Vĩnh Long',
    'Vĩnh Phúc',
    'Yên Bái',
    'Khác',
  ],
};
